### ISSUE TITLE
Usage of GPT2 as diffusion model

### ISSUE THREAD

**Issue by marzi-heidari** [YDU-uva/ProtoDiff#1]
I read your paper recently and you mentioned that a GPT2 based model is used for the diffusion process. Given that GPT2 model is designed and trained for text input how did you use it for image embeddings?

Also, when are you planning to release the code?

**Comment by YDU-uva** [comment]
Hi Marzi:

Thanks for your interesting to our paper.  We do not use pertained GPT2, we just use GPT2 architecture. We follow the code from “https://github.com/wpeebles/G.pt”.

We will release the code asap.  If you have any questions, pls let me know.

Best,
Yingjun

2023年10月26日 16:59，Marzi Heidari ***@***.***> 写道：



I read your paper recently and you mentioned that a GPT2 based model is used for the diffusion process. Given that GPT2 model is designed and trained for text input how did you use it for image embeddings?

Also, when are you planning to release the code?

**Comment by marzi-heidari** [comment]
I appreciate your swift response :)
